package server.movement;

/**
 * @Author Arnah
 * @Website http://Vertisy.ca/
 * @since Jun 22, 2017
 */
public class MovePathAttribute{

	public static final int
	/*NORMAL = 0,
	JUMP = 1,
	IMPACT = 2,
	IMMEDIATE = 3,
	TELEPORT = 4,
	HANGONBACK = 5,
	ASSAULTER = 6,
	ASSASSINATION = 7,
	RUSH = 8,
	STATCHANGE = 9,
	SITDOWN = 10,
	STARTFALLDOWN = 11,
	FALLDOWN = 12,
	STARTWINGS = 13,
	WINGS = 14,
	ARAN_ADJUST = 15,
	MOB_TOSS = 16,
	FLYING_BLOCK = 17,
	DASH_SLIDE = 18,
	BMAGE_ADJUST = 19,
	FLASHJUMP = 20,
	ROCKET_BOOSTER = 21,
	BACKSTEP_SHOT = 22,
	MOBPOWERKNOCKBACK = 23,
	VERTICALJUMP = 24,
	CUSTOMIMPACT = 25,
	COMBATSTEP = 26,
	HIT = 27,
	TIMEBOMBATTACK = 28,
	SNOWBALLTOUCH = 29,
	BUFFZONEEFFECT = 30,
	MOB_LADDER = 31,
	MOB_RIGHTANGLE = 32,
	MOB_STOPNODE_START = 33,
	MOB_BEFORE_NODE = 34,
	MOB_ATTACK_RUSH = 35,
	MOB_ATTACK_RUSH_STOP = 36;*/
	NORMAL = 0, JUMP = 1, IMPACT = 2, IMMEDIATE = 3, TELEPORT = 4, HANGONBACK = 5, ASSAULTER = 6, ASSASSINATION = 7, RUSH = 8, STATCHANGE = 9, SITDOWN = 10, STARTFALLDOWN = 11, FALLDOWN = 12, STARTWINGS = 13, WINGS = 14, ARAN_ADJUST = 15, MOB_TOSS = 16, FLYING_BLOCK = 17, DASH_SLIDE = 18, BMAGE_ADJUST = 19, FLASHJUMP = 20, ROCKET_BOOSTER = 21, BACKSTEP_SHOT = 22, MOBPOWERKNOCKBACK = 23, VERTICALJUMP = 24, CUSTOMIMPACT = 25, COMBATSTEP = 26, HIT = 27, TIMEBOMBATTACK = 28, SNOWBALLTOUCH = 29, BUFFZONEEFFECT = 30, MOB_LADDER = 31, MOB_RIGHTANGLE = 32, MOB_STOPNODE_START = 33, MOB_BEFORE_NODE = 34, MOB_ATTACK_RUSH = 35, MOB_ATTACK_RUSH_STOP = 36;
}